# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20181023_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to=market.models.get_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to=market.models.get_path),
        ),
    ]
